apiVersion: batch/v1
kind: CronJob
metadata:
  name: news-downloader-cron
  namespace: news-pipeline
spec:
  # Ejecutar cada hora
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: news-downloader
        spec:
          containers:
          - name: downloader
            image: proyecto_downloader:latest
            imagePullPolicy: Never
            volumeMounts:
            - name: shared-data
              mountPath: /app/data
            env:
            - name: SLEEP_INTERVAL
              value: "0"  # No loop en CronJob
          volumes:
          - name: shared-data
            persistentVolumeClaim:
              claimName: news-data-pvc
          restartPolicy: OnFailure