apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-economic
  namespace: news-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: news-economic
  template:
    metadata:
      labels:
        app: news-economic
    spec:
      containers:
        - name: economic
          image: proyecto_economic_data:latest
          imagePullPolicy: Never
          env:
            - name: SLEEP_INTERVAL
              value: "3600"
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: gemini-secret
                  key: api-key
          volumeMounts:
            - name: shared-data
              mountPath: /app/data
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: news-data-pvc