apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-processor
  namespace: news-pipeline
spec:
  replicas: 2  # Escalable para procesamiento paralelo
  selector:
    matchLabels:
      app: news-processor
  template:
    metadata:
      labels:
        app: news-processor
    spec:
      containers:
        - name: processor
          image: proyecto_processor:latest
          imagePullPolicy: Never
          env:
            - name: SLEEP_INTERVAL
              value: "1800"
          volumeMounts:
            - name: shared-data
              mountPath: /app/data
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: news-data-pvc