apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-downloader
  namespace: news-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: news-downloader
  template:
    metadata:
      labels:
        app: news-downloader
    spec:
      containers:
        - name: downloader
          image: proyecto-downloader:latest
          imagePullPolicy: Never
          env:
            - name: SLEEP_INTERVAL
              value: "3600"
          volumeMounts:
            - name: shared-data
              mountPath: /app/data
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
      volumes:
        - name: shared-data
          persistentVolumeClaim:
            claimName: news-data-pvc